GET http://localhost:3000/users

####
POST http://localhost:3010/register 
Content-Type: application/json 

{
  "username": "saara",
  "name": "Adam Richard",
  "password": "123Kadafd",
  "gender": "male",
  "location": "Detroit"
}


###



//login success
POST https://srb-user-data.onrender.com/login
Content-Type: application/json 

{
  "username": "sagar Babu",
  "password": "123@msbg"
}



###


//invalid password
POST http://localhost:3000/login
Content-Type: application/json 

{
  "username": "adam_richards",
  "password": "richard_568"
}

###
PUT https://srb-user-data.onrender.com/change-password 
Content-Type: application/json

{
  "username": "sagar",
  "oldPassword": "123Kadafd",
  "newPassword": "richard@456"
}
